[package]
name = "trapify"
version = "0.1.0"
edition = "2021"

[dependencies]
comfy = "0.3" # It seems 0.4 has some problems with trunk build

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 1
